import { readdirSync, readFileSync } from "node:fs";
import { basename, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

export const projectRoot = fileURLToPath(new URL("../", import.meta.url));

export type MapCard = Readonly<{
  path: string;
  id: string;
  type: string;
  title: string;
  universe: string;
  status: string;
  updated: string;
  revision: string;
}>;

const ignoredDirectories = new Set([
  ".git",
  "node_modules",
  ".next",
  ".turbo",
  ".local",
  "dist",
  "coverage",
]);

export function listFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true })
    .sort((first, second) => first.name.localeCompare(second.name, "en"))
    .flatMap((entry) => {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) {
        return ignoredDirectories.has(entry.name) ? [] : listFiles(path);
      }
      return entry.isFile() ? [path] : [];
    });
}

export function readText(path: string): string {
  return readFileSync(path, "utf8");
}

function readField(frontmatter: string, name: string, path: string): string {
  const value = frontmatter.match(new RegExp(`^${name}: (.+)$`, "m"))?.[1];
  if (!value || value.includes("|")) {
    throw new Error(`${relative(projectRoot, path)}: missing/invalid ${name}`);
  }
  return value;
}

export function readMapCards(): MapCard[] {
  const shelves = ["objects", "processes", "decisions", "sessions"];
  return shelves.flatMap((shelf) =>
    listFiles(join(projectRoot, "map", shelf))
      .filter(
        (path) =>
          path.endsWith(".md") && basename(path) !== "CONTEXT.md" && basename(path) !== "_index.md",
      )
      .map((path) => {
        const frontmatter = readText(path).match(/^---\n([\s\S]*?)\n---\n/)?.[1];
        if (!frontmatter) throw new Error(`${path}: missing frontmatter`);
        return {
          path,
          id: readField(frontmatter, "id", path),
          type: readField(frontmatter, "type", path),
          title: readField(frontmatter, "title", path),
          universe: readField(frontmatter, "universe", path),
          status: readField(frontmatter, "status", path),
          updated: readField(frontmatter, "updated", path),
          revision: readField(frontmatter, "revision", path),
        };
      }),
  );
}

export function createMapOutputs(): ReadonlyMap<string, string> {
  const mapDirectory = join(projectRoot, "map");
  const cards = readMapCards();
  const rows = cards.map(
    (card) =>
      `| [${card.title}](${relative(mapDirectory, card.path).replaceAll("\\", "/")})` +
      ` | ${card.type} | ${card.universe} | ${card.status} | ${card.updated} |`,
  );
  const catalog = [
    "# ICM catalog",
    "",
    "<!-- Generated by scripts/generate-map.ts. Edit source cards, not this file. -->",
    "",
    "| Card | Type | Universe | Status | Updated |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
  const objectRows = cards
    .filter((card) => card.type === "object")
    .map(
      (card) =>
        `- [${card.title}](${relative(join(mapDirectory, "objects"), card.path).replaceAll("\\", "/")})` +
        ` — ${card.universe}; ${card.status}; ${card.updated}.`,
    );
  const objectIndex = [
    "# Objects",
    "",
    "<!-- Generated by scripts/generate-map.ts. Edit source cards, not this file. -->",
    "",
    ...objectRows,
    "",
  ].join("\n");
  const routing = readText(join(mapDirectory, "CLAUDE.md"));
  return new Map([
    [join(mapDirectory, "catalog.md"), catalog],
    [join(mapDirectory, "objects", "_index.md"), objectIndex],
    [join(mapDirectory, "AGENTS.md"), routing],
    [join(mapDirectory, "routing.md"), routing],
  ]);
}
